obj_name=seatrace-app
net_collector_ip=scouter
net_collector_udp_port=6100
net_collector_tcp_port=6100

hook_method_patterns=org.example.seatrace.controller.*.*,org.example.seatrace.service.*.*,org.example.seatrace.repository.*.*
profile_spring_controller_method_parameter_enabled=false
profile_http_header_enabled=true
trace_http_client_ip_header_key=X-Forwarded-For
counter_interaction_enabled=true
profile_sql_enabled=true
profile_connection_open_enabled=true
profile_socket_open_enabled=true
profile_http_querystring_enabled=true
