create table reservation_hold_deadletters (
    id bigint generated by default as identity primary key,
    reservation_ids text not null,
    source varchar(20) not null,
    chunk_size int not null,
    error_type varchar(100),
    error_message text,
    created_at timestamp not null,
    updated_at timestamp not null
);
