create table users (
    id bigint generated by default as identity primary key,
    email varchar(100) not null,
    password_hash varchar(100) not null,
    name varchar(20) not null,
    role varchar(10) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table venues (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    location varchar(255) not null
);

create table seats (
    id bigint generated by default as identity primary key,
    venue_id bigint not null,
    section varchar(30) not null,
    row_no varchar(10) not null,
    seat_no varchar(10) not null,
    grade varchar(20) not null
);

create table events (
    id bigint generated by default as identity primary key,
    venue_id bigint not null,
    name varchar(100) not null,
    start_at timestamp not null,
    end_at timestamp not null,
    status varchar(20) not null
);

create table event_seats (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    seat_id bigint not null,
    price numeric(10, 2) not null,
    status varchar(20) not null,
    held_until timestamp null
);

create table reservations (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    event_id bigint not null,
    status varchar(20) not null,
    total_amount numeric(10, 2) not null default 0,
    expires_at timestamp null
);

create table reservation_seats (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null,
    event_seat_id bigint not null
);

alter table event_seats
    add constraint fk_event_seats_event
    foreign key (event_id) references events(id);

alter table event_seats
    add constraint fk_event_seats_seat
    foreign key (seat_id) references seats(id);

alter table event_seats
    add constraint uq_event_seats_event_seat
    unique (event_id, seat_id);

alter table seats
    add constraint fk_seats_venue
    foreign key (venue_id) references venues(id);

alter table events
    add constraint fk_events_venue
    foreign key (venue_id) references venues(id);

alter table reservations
    add constraint fk_reservations_user
    foreign key (user_id) references users(id);

alter table reservations
    add constraint fk_reservations_event
    foreign key (event_id) references events(id);

alter table reservation_seats
    add constraint fk_reservation_seats_reservation
    foreign key (reservation_id) references reservations(id);

alter table reservation_seats
    add constraint fk_reservation_seats_event_seat
    foreign key (event_seat_id) references event_seats(id);

alter table reservation_seats
    add constraint uq_reservation_seats_event_seat
    unique (event_seat_id);
