alter table seats
    add constraint uq_seats_venue_section_row_seat
    unique (venue_id, section, row_no, seat_no);

create table seat_audit_logs (
    id bigint generated by default as identity primary key,
    venue_id bigint not null,
    action varchar(50) not null,
    actor varchar(100) not null,
    detail varchar(500) not null,
    created_at timestamp not null
);

alter table seat_audit_logs
    add constraint fk_seat_audit_logs_venue
    foreign key (venue_id) references venues(id);
